<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SmokeTest</AssemblyName>
    <RootNamespace>SmokeTest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" Version="11.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/SerialDebugTool/SerialDebugTool.csproj" />
  </ItemGroup>

</Project>
